spring.application.name=ChatApp


# for db connecction
spring.datasource.url=jdbc:mysql://localhost:3306/chat_app?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=1234


# orm 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# variables

jwt.secret-key=akjlas33@#fasdfjksadf3212jkLKJsefe
jwt.expiration-minutes=60


# this is email service

mailjet.api.public=e3ea1a99296166ea862cc5b755b8766d
mailjet.api.private=1097f443f7332ebe86a1d909ba403f3f
mailjet.sender=nikhilgaikwadmh10@gmail.com


# List of allowed frontend origins
app.cors.allowed-origins=http://localhost:5173,https://your-production-frontend.com

app.timezone=Asia/Kolkata


app.api-prefix=/api